source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               plugin.properties,\
               plugin_ko.properties,\
               plugin_ja.properties,\
               plugin_zh.properties,\
               icons/
